import { StyleSheet } from 'react-native';
import { StyleConstants } from './StyleConstants';

export const Layout = StyleSheet.create({
  f1: { flex: 1 },
  f2: { flex: 2 },
  f3: { flex: 3 },
  mx1: { marginRight: StyleConstants.size1, marginLeft: StyleConstants.size1 },
  mt0: {marginTop: 0},
  mb1: { marginBottom: StyleConstants.size1 },
  mt1: { marginTop: StyleConstants.size1 },
  ml1: { marginLeft: StyleConstants.size1 },
  mr1: { marginRight: StyleConstants.size1 },
  mx2: { marginRight: StyleConstants.size2, marginLeft: StyleConstants.size2 },
  mb2: { marginBottom: StyleConstants.size2 },
  mt2: { marginTop: StyleConstants.size2 },
  ml2: { marginLeft: StyleConstants.size2 },
  mr2: { marginRight: StyleConstants.size2 },
  mt3: { marginTop: StyleConstants.size3 },
  px0: { paddingLeft: 0, paddingRight: 0},
  p1: { padding: StyleConstants.size1 },
  px1: {
    paddingRight: StyleConstants.size1,
    paddingLeft: StyleConstants.size1,
  },
  py1: {
    paddingTop: StyleConstants.size1,
    paddingBottom: StyleConstants.size1,
  },
  pr1: { paddingRight: StyleConstants.size1 },
  pb1: { paddingBottom: StyleConstants.size1 },
  pt1: { paddingTop: StyleConstants.size1 },
  p2: { padding: StyleConstants.size2 },
  px2: {
    paddingLeft: StyleConstants.size2,
    paddingRight: StyleConstants.size2,
  },
  py2: {
    paddingTop: StyleConstants.size2,
    paddingBottom: StyleConstants.size2,
  },
  pb2: { paddingBottom: StyleConstants.size2 },
  pt2: { paddingTop: StyleConstants.size2 },
  pl2: { paddingLeft: StyleConstants.size2 },
  pr2: { paddingRight: StyleConstants.size2 },
  row: { flexDirection: 'row' },
  col: { flexDirection: 'column' },
  aCenter: { alignItems: 'center' },
  aStart: { alignItems: 'flex-start' },
  aEnd: { alignItems: 'flex-end' },
  jSpace: { justifyContent: 'space-between' },
  jCenter: { justifyContent: 'center' },
  jStart: { justifyContent: 'flex-start'},
  jEnd: { justifyContent: 'flex-end'},
  iconHeight: { height: StyleConstants.iconWidth },
  center: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  container: {
    flex: 1,
    margin: StyleConstants.size2,
    flexDirection: 'column',
  },
});
